version: '3'

services:
  url-shortener:
    container_name: url-shortener
    image: node
    ports:
      - '31857:31857'
    volumes:
      - /home/deploy/url-shortener:/code
    working_dir: /code
    command: npm start
    restart: always