name: Deploy to VPS

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm i

      - name: Run compile task
        run: npm run compile

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
          TARGET: /home/${{ secrets.DEPLOY_SERVER_USER }}/url-shortener

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.DEPLOY_SERVER_USER }}/url-shortener
            docker-compose down -v
            docker-compose up -d